### PR TITLE
fix: prettier

### PR DESCRIPTION
**Pull request by MLopezJ**
executed command: npx prettier -w ./

### CODE REVIEW

**Comment by MLopezJ** [comment]
This solves the current breaked test in the `saga` branch. More info https://github.com/NordicSemiconductor/asset-tracker-cloud-docs/actions/runs/6889373116/job/18740228806

**Comment by coderbyheart** [comment]
Don't format minified sources. Those should be ignored from prettifying.

**Comment by coderbyheart** [comment]
Because prettifying defeats the purpose of minification!

**Comment by coderbyheart** [comment]
In addition, style changes should be committed as `style: ...`, they are not fixing anything in the software.

**Pull request merged**
