### PR TITLE
provide schemas as module

### PR DESCRIPTION
**Pull request by coderbyheart**
This exports the protocol schemas as an NPM
module so they can be imported in nRF Asset Tracker
projects that need to send or retrieve messages.

### CODE REVIEW

**Comment by umapraseeda** [comment]
There seems to be a doc build error? Docs seem to be not updated in the artifact.

**Comment by coderbyheart** [comment]
Changes to content are minimal and exact replication of already approved content.

**Comment by GilDev** [comment]
There are still links to the old schemas [in the docs](https://nordicsemiconductor.github.io/asset-tracker-cloud-docs/v2.1.x/docs/aws/IoTShadowAndTopics.html).

**Comment by coderbyheart** [comment]
@GilDev is this a problem for you?

**Comment by GilDev** [comment]
Not directly, it was just for information as some of those links point to 404 errors (for example this one: https://github.com/NordicSemiconductor/asset-tracker-cloud-docs/blob/saga/docs/cloud-protocol/state.reported.schema.json). They could also maybe be outdated at some point compared to the new schemas?

**Comment by coderbyheart** [comment]
Ah, yes it seems some document does not use a permalink. Can you share which page you found that link on? Thanks!

**Comment by GilDev** [comment]
Sure! The “[JSON schema file](https://nordicsemiconductor.github.io/asset-tracker-cloud-docs/v2.1.x/docs/cloud-protocol/state.reported.aws.schema.json)” hyperlink of the “[AWS IoT Device Shadow service and MQTT topics](https://nordicsemiconductor.github.io/asset-tracker-cloud-docs/v2.1.x/docs/aws/IoTShadowAndTopics.html)” page contains dead links in the `$id` and `$ref` parameters.

These seems to be the only ones I found on this page.

**Comment by coderbyheart** [comment]
Ah, yes, right! We have that fixed in newer releases, but will fix it for the older branches! Thanks again!

**Pull request merged**
