### PR TITLE
feat: updated design, now similar to nrf Connect SDK

### LINKED ISSUE #465: Adapt new Nordic docs layout style
A new layout has been introduced to [developer.nordicsemi.com](https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/applications/asset_tracker_v2/README.html), and the nRF Asset Tracker docs need to follow this.

Theme source: https://github.com/nrfconnect/doc-sphinx-ncs-theme

Image

- [ ] contact @umapraseeda and Richa Pandey before beginning to work on this

### PR DESCRIPTION
**Pull request by KajaKoren**
New design implemented, based on the theme created for nrf Connect SDK docs, using [sphinx-ncs-theme](https://github.com/nrfconnect/doc-sphinx-ncs-theme). Some minor changed done to the design in order to make it fit this documentation. 

Fixes #465

### CODE REVIEW

**Review by coderbyheart — CHANGES_REQUESTED** [review]
- Add link to `saga`  
  image
- Please check if we need the JavaScript.
- Ensure colors match  
  image
- Remove scrolling of headlines  
  image

**Comment by KajaKoren** [comment]
Screenshot from 2022-09-19 15-27-12
Updated now.

Only way I managed to remove "nRF Asset Tracker" header on the left side was by setting display:none in the css file.

**Review by coderbyheart — APPROVED** [review]

**Comment by coderbyheart** [comment]
@umapraseeda @richabp ready for review.

**Review by peknis — APPROVED** [review]

**Comment by umapraseeda** [comment]
In the mobile view also, could we make 'saga' visible in the version drop-down (as in the desktop view)?

**Comment by umapraseeda** [comment]
Also, https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/index.html has an option of hiding search matches after a search result is opened. This could be a nice add-on.

**Review by richabp — COMMENTED** [review]
In earlier doc versions, switching back to "saga" version is missing. It would be good to have it so that switching between the versions would be possible.

**Comment by coderbyheart** [comment]
> In earlier doc versions, switching back to "saga" version is missing. It would be good to have it so that switching between the versions would be possible.

The old version don't have these links right now, and it's out of scope of this PR.

**Comment by coderbyheart** [comment]
> In the mobile view also, could we make 'saga' visible in the version drop-down (as in the desktop view)?

Fixed in b33de0b45

**Comment by coderbyheart** [comment]
> Also, https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/index.html has an option of hiding search matches after a search result is opened. This could be a nice add-on.

Fixed in 846febac7e6d279bcd774361a7e2aecf3237c251

**Review by richabp — COMMENTED** [review]
Is this navbar ( appearing in iPad Mini, iPad Air, Surface Pro 7) required here as we have only one docset 'Asset Tracker'? This is added in NCS as it has other docsets like nrfx etc. 
image

**Comment by coderbyheart** [comment]
> Is this navbar ( appearing in iPad Mini, iPad Air, Surface Pro 7) required here as we have only one docset 'Asset Tracker'? This is added in NCS as it has other docsets like nrfx etc. image

Good find, the behaviour was a bit inconsisten on medium screen width.

Fixed in fe2737f32d955367f8985c7ecd757154f58e85cb

**Review by umapraseeda — APPROVED** [review]

**Review by richabp — APPROVED** [review]

**Pull request merged**
